online_library/library/urls.py
from django.urls import path
from . import views
app_name = "library"

urlpatterns = [
    path("new-material/<course>",views.CreateMaterial.as_view(),name="creatematerial"),
    path("edit-material/<int:pk>",views.UpdateMaterial.as_view(),name="updatematerial"),
    path("delete-material/<int:pk>",views.DeleteMaterial.as_view(),name="deletematerial"),
    path("courses",views.CourseList.as_view(),name="courselist"),
    path("course/<int:pk>/",views.CourseDetail.as_view(),name="coursedetail"),
    path("course/material/<int:pk>/review",views.add_review,name="add_review"),
    path("search/",views.search_course,name="search"),
    path("courses/filtered",views.filter,name="filter")
]

online_library/online_library/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import urls
from library import urls
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.HomePage.as_view(),name="home"),
    path("accounts/",include("accounts.urls",namespace="accounts")),
    path("library/",include("library.urls",namespace="library")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_library/library/models.py
from django.db import models
from accounts.models import User
# Create your models here.

class Level(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):

        return f"{self.name}"
class Faculty(models.Model):
    name = models.CharField(max_length=100)
    class Meta:
        verbose_name_plural = "faculties"
    def __str__(self):

        return f"{self.name}"


class Department(models.Model):
    name = models.CharField(max_length=100)
    faculty = models.ForeignKey(Faculty,related_name = "departments", on_delete= models.CASCADE)
    def __str__(self):

        return f"{self.name}"
class Course(models.Model):
    level = models.ForeignKey(Level,related_name="courses",on_delete=models.CASCADE)
    code = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    credit_unit = models.CharField(max_length=2)
    outline = models.TextField(max_length=300)
    department = models.ForeignKey(Department,related_name="courses",on_delete= models.CASCADE)
    faculty = models.ForeignKey(Faculty,related_name="courses",on_delete=models.CASCADE)
    def __str__(self):

        return f"{self.code}"
class Material(models.Model):
    name = models.CharField(max_length=100)
    file = models.FileField(upload_to = "documents")
    course = models.ForeignKey(Course,related_name= "materials",on_delete= models.CASCADE)
    preview = models.TextField(max_length=100)
    def __str__(self):

        return f"{self.name}"
class Review(models.Model):
    material = models.ForeignKey(Material,related_name="reviews",on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name="reviews",on_delete=models.CASCADE)
    rating = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.user.username

online_library/library/forms.py
from django import forms
from .models import Material,Review,Faculty,Department,Level

class CreateMaterialForm(forms.ModelForm):
    class Meta():
        model = Material
        fields = ("name","file","preview")
        widgets = {
             "name" : forms.TextInput(attrs={"class":"",}),
             "file" : forms.FileInput(attrs={"class":"",}),
             "preview" : forms.Textarea(attrs={"class":"",}),
        }
class ReviewForm(forms.ModelForm):
    ratings = [
    ("","Rate material"),
    (5,"⭐⭐⭐⭐⭐"),
    (4,"⭐⭐⭐⭐"),
    (3,"⭐⭐⭐"),
    (2,"⭐⭐"),
    (1,"⭐"),
    ]
    rating = forms.ChoiceField(choices=ratings,widget=forms.Select(attrs={}))
    class Meta:
        model = Review
        fields = ["rating"]

class FilterForm(forms.Form):

    faculties = [("","Faculty")]
    faculties.extend([(faculty.name,faculty.name) for faculty in Faculty.objects.all()])
    faculty = forms.ChoiceField(choices=faculties,required=False)

    departments = [("","Department")]
    departments.extend([(department.name,department.name) for department in Department.objects.all()])
    department = forms.ChoiceField(choices= departments,required=False)

    levels = [("","Level")]
    levels.extend([(level.name,level.name) for level in Level.objects.all()])
    level = forms.ChoiceField(choices=levels,required=False)

online_library/library/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import Avg,Q
from django.views.generic import CreateView,ListView,DetailView,UpdateView,DeleteView
from .models import Material,Course,Faculty,Department,Level,Review
from accounts.models import User,Uploader
from .forms import CreateMaterialForm,ReviewForm,FilterForm
from django.urls import reverse_lazy
from django.conf import settings
from django.views.generic.edit import FormMixin
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.template.loader import render_to_string

# Create your views here.
class UploaderOnlyMixin(UserPassesTestMixin):
    def test_func(self):
        try:
            uploader = Uploader.objects.get(user=self.request.user)
            return True
        except Uploader.DoesNotExist:
            return False

class CreateMaterial(UploaderOnlyMixin,CreateView):
    model = Material
    form_class = CreateMaterialForm
    template_name = "materialform.html"
    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.course = Course.objects.get(code=self.kwargs.get("course"))
        self.object.save()

        return super().form_valid(form)
    def get_success_url(self):
        return reverse_lazy("library:coursedetail",kwargs= {"pk":self.object.course.pk})

class UpdateMaterial(UploaderOnlyMixin,UpdateView):
    model = Material
    form_class = CreateMaterialForm
    template_name = "materialform.html"
    def get_success_url(self):
        return reverse_lazy("library:coursedetail",kwargs= {"pk":self.object.course.pk})

class DeleteMaterial(UploaderOnlyMixin,DeleteView):
    model = Material
    template_name = "material_delete.html"
    def get_success_url(self):
        return reverse_lazy("library:coursedetail",kwargs= {"pk":self.object.course.pk})
class CourseList(ListView):
    model = Course
    template_name = "courses.html"
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] =  FilterForm
        context["departments"] = Department.objects.all()
        return context


class CourseDetail(DetailView):
    model = Course
    template_name = "course.html"
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ReviewForm
        context["media"] = settings.MEDIA_URL
        course = Course.objects.get(pk=self.kwargs.get("pk"))
        if Review.objects.filter(user=self.request.user):
            context["reviewed"] = True
        else:
            context["reviewed"] = False

        return context

@login_required
def add_review(request, pk):
    material = get_object_or_404(Material, pk=pk)
    if request.method=="POST":
        review = Review.objects.create(
        material = material,
        user = request.user,
        rating = request.POST.get("rating")
        )

        average_rating = Review.objects.filter(material=material).aggregate(rating=Avg("rating"))
        context = {
        "user" : request.user.username,
        "rating" : request.POST.get("rating"),
        "average_rating":average_rating

        }
        return JsonResponse(
            {
            "bool":True,
            "context":context
            })


def search_course(request):
    if request.method == "POST":
        q = request.POST["q"]
        if q:
            courses = Course.objects.filter(Q(title__icontains=q)|Q(code__icontains=q)).distinct()
    return render(request, 'base.html', {'results': courses})

def filter(request):
    if request.method == "POST":
        courses = Course.objects.all()
        if request.POST["faculty"] != "":
            faculty = Faculty.objects.get(name=request.POST["faculty"])
            courses = courses.filter(faculty=faculty)

        if request.POST["department"] != "":
            department = Department.objects.get(name=request.POST["department"])
            courses = courses.filter(department=department)

        if request.POST["level"] != "":
            level = Level.objects.get(name=request.POST["level"])
            courses = courses.filter(level=level)

        context = {
            "courses":courses
        }
        data =  render_to_string("filtered.html",context)
        return JsonResponse(
            {
            "data":data
            })

online_library/library/templates/course.html
{% extends "base.html" %}
{% block content %}
    <p></p>
    <h3>Title : {{ course.title }}</h3>
    <p></p>
    <h3>Code : {{ course.code }}</h3>
    <p></p>
    <h3>Outline : {{ course.outline}}</h3>
    <p></p>

    <h4>Materials:</h4>
    {% for material in course.materials.all %}
    <div class="">
      <h5>{{material.name}}</h5>
      <a class="btn btn-dark btn-sm"href="{{media}}{{material.file}}" download ={{material.name}}>
        download</a>
        <a class="btn btn-dark btn-sm" href="{% url 'library:deletematerial' pk=material.pk%}">delete</a>
        <a class="btn btn-dark btn-sm" href="{% url 'library:updatematerial' pk=material.pk%}">update</a>
        <p></p>
        <h6>Reviews:</h6>
        <div class="reviewlist">
          {% for review in material.reviews.all %}
          <p>{{ review.user }} -- {{ review.rating }}</p>
          <p></p>
          {% endfor %}

        </div>
        {% if user.is_authenticated %}
          {% if not reviewed%}
        <form class="reviewform" action="{% url 'library:add_review' pk=material.pk %}"method="post">
          {% csrf_token %}
          {{form}}
          <input type="submit" name="" value="submit">
        </form>
        {% endif %}
        {% endif %}
        <p></p>
    </div>
    <p></p>

    {% endfor %}

    {% if is_uploader %}
    <a href="{% url 'library:creatematerial' course=course%}">new material</a>
    {% endif %}
{% endblock %}

online_library/library/templates/courses.html
{% extends "base.html" %}
{% block content %}
<form class="filterform" method="post" action="{% url 'library:filter'%}">
  {% csrf_token %}
  {{ form.faculty }}
  {{ form.department }}
  {{ form.level}}
</form>
<div class="list">

  {% for course in course_list %}
  <div class="course" department = "{{course.department.name}}" faculty="{{course.faculty.name}}" level="{{course.level.name}}">
    <p></p>
    <h4>{{course.code}}-{{course.title}}</h4>
    <p></p>
    <a href="{% url 'library:coursedetail' pk=course.pk%}" class="btn btn-dark">view course</a>
  </div>
  {% endfor %}
</div>

  {% for department in departments.all %}
    <div testdata ="{{department.name}}-{{department.faculty.name}}"  class="store"></div>
  {% endfor %}

  <!-- jquery for filter function -->

{% endblock %}

online_library/library/templates/filtered.html
{% for course in courses %}
<div class="course" department = "{{course.department.name}}" faculty="{{course.faculty.name}}" level="{{course.level.name}}">
  <p></p>
  <h4>{{course.code}}-{{course.title}}</h4>
  <p></p>
  <a href="{% url 'library:coursedetail' pk=course.pk%}" class="btn btn-dark">view course</a>
</div>
{% endfor %}

online_library/library/templates/material_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">
  {% csrf_token%}
  <input type="submit" name="" value="delete">
</form>
{% endblock %}

online_library/library/templates/materialform.html
{% extends "base.html" %}
{% block content %}
  <form class="" enctype="multipart/form-data" method="post">
    {% csrf_token%}
    {{ form.as_p }}
    <input type="submit" name="" value="dhudhu">
  </form>
{% endblock %}