online_library/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = "accounts"
urlpatterns = [
    path("signup/",views.SignUp.as_view(),name="signup"),
    path("logout/",views.logout_user,name="logout"),
    path("login/",views.loginuser, name="login"),
    path("become_an_uploader/",views.CreateUploader.as_view(),name="createuploader")
]

online_library/library/urls.py
from django.urls import path
from . import views
app_name = "library"

urlpatterns = [
    path("new-material/<course>",views.CreateMaterial.as_view(),name="creatematerial"),
    path("edit-material/<int:pk>",views.UpdateMaterial.as_view(),name="updatematerial"),
    path("delete-material/<int:pk>",views.DeleteMaterial.as_view(),name="deletematerial"),
    path("courses",views.CourseList.as_view(),name="courselist"),
    path("course/<int:pk>/",views.CourseDetail.as_view(),name="coursedetail"),
    path("course/material/<int:pk>/review",views.add_review,name="add_review"),
    path("search/",views.search_course,name="search"),
    path("courses/filtered",views.filter,name="filter")
]

online_library/online_library/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import urls
from library import urls
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.HomePage.as_view(),name="home"),
    path("accounts/",include("accounts.urls",namespace="accounts")),
    path("library/",include("library.urls",namespace="library")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_library/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'css/master.css'%}"> -->
    <meta name="viewport" content="width=device-width, initial-scale=0.8">

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
      <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            <a class="nav-link" href="#">About Us</a>
          </div>
          {% if user.is_authenticated %}
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'library:courselist'%}">Courses</a>
            {%if not is_uploader%}
            <a class="nav-link" href="{% url 'accounts:createuploader'%}">become an uploder</a>
            {% endif %}
            <a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a>
          </div>
          {% else %}
          <div class="navbar-nav ms-auto">
            <a class="nav-link" href="{% url 'accounts:login'%}">Login</a>
            <a class="nav-link" href="{% url 'accounts:signup'%}">Singup</a>
          </div>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container">
      {% if user.is_authenticated %}
      <form class="" action="{% url 'library:search'%}" method="post">
        {%csrf_token%}
        <input type="text" name="q" value="">
        <input type="submit" name="" value="">
      </form>
      {% endif %}
      {% if results %}
      {%for course in results%}
      <div class="course" department = "{{course.department.name}}" faculty="{{course.faculty.name}}" level="{{course.level.name}}">
        <p></p>
        <h4>{{course.code}}-{{course.title}}</h4>
        <p></p>
        <a href="{% url 'library:coursedetail' pk=course.pk%}" class="btn btn-dark">view course</a>
      </div>
      {%endfor%}
      {%endif%}
      {{ request.user }}
      {% block content %}
      {% endblock %}
    </div>

  </body>
</html>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
<script src="{% static 'js/lb.js'%}" charset="utf-8"></script>

online_library/templates/home.html
{% extends "base.html" %}
{% block content %}
<p>home</p>
{% endblock %}